- name: Configure VPS
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Install Certbot
      apt:
        name: certbot
        state: present
    - name: Obtain TLS Certificate
      command: >
        certbot --nginx -d www.herkuskrisciunas.me -d herkuskrisciunas.com